"""empty message

Revision ID: 386edb3fbafa
Revises: 
Create Date: 2024-05-07 00:30:20.115266

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '386edb3fbafa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creator_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('html', sa.String(), nullable=False),
                    sa.Column('created_date', sa.Date(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('internal', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_template_id'), 'template', ['id'], unique=False)
    op.create_table(
        'mail', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('creation_date', sa.DateTime(), nullable=True),
        sa.Column('update_date', sa.DateTime(), nullable=True),
        sa.Column('sender_id', sa.Integer(), nullable=False),
        sa.Column('receiver_id', sa.String(), nullable=False),
        sa.Column('template_id', sa.Integer(), nullable=True),
        sa.Column('subject', sa.String(), nullable=True),
        sa.Column('receiver_mail', sa.String(), nullable=True),
        sa.Column('fields', sa.String(), nullable=True),
        sa.Column('sent', sa.Boolean(), nullable=True),
        sa.Column('priority', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['template_id'],
            ['template.id'],
        ), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_mail_id'), 'mail', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mail_id'), table_name='mail')
    op.drop_table('mail')
    op.drop_index(op.f('ix_template_id'), table_name='template')
    op.drop_table('template')
    # ### end Alembic commands ###
