"""empty message

Revision ID: 6a212e0e0b92
Revises: 0bae1f81d197
Create Date: 2023-11-17 02:52:48.849082

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6a212e0e0b92'
down_revision = '0bae1f81d197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocaching', sa.Column('code',
                                            sa.String(),
                                            nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('code'))
    op.create_index(op.f('ix_geocaching_code'),
                    'geocaching', ['code'],
                    unique=False)
    op.create_table('user_geocaching',
                    sa.Column('user_code', sa.String(), nullable=False),
                    sa.Column('code', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['code'],
                        ['geocaching.code'],
                    ), sa.ForeignKeyConstraint(
                        ['user_code'],
                        ['user.code'],
                    ), sa.PrimaryKeyConstraint('user_code', 'code'))
    op.add_column(
        'user', sa.Column('lleidacoins_claimed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lleidacoins_claimed')
    op.drop_table('user_geocaching')
    op.drop_index(op.f('ix_geocaching_code'), table_name='geocaching')
    op.drop_table('geocaching')
    # ### end Alembic commands ###
