"""empty message

Revision ID: 7c00e3578952
Revises: 550878b33149
Create Date: 2023-08-22 00:49:49.880618

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7c00e3578952'
down_revision = '550878b33149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lleida_hacker', 'logo')
    op.add_column('user', sa.Column('created_at', sa.DateTime(),
                                    nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(),
                                    nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.add_column(
        'lleida_hacker',
        sa.Column('logo', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
