"""empty message

Revision ID: e26348b569eb
Revises: a67851c0d7d4
Create Date: 2023-10-12 01:36:35.663075

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e26348b569eb'
down_revision = 'a67851c0d7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column('recive_mails', sa.Boolean(), nullable=True, default=True))
    op.execute('UPDATE "user" SET recive_mails = true')
    op.alter_column('user', 'recive_mails', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'recive_mails')
    # ### end Alembic commands ###
