"""empty message

Revision ID: 4b8ee8394bcb
Revises: bd9a70ee3cae
Create Date: 2023-09-11 17:03:28.383559

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4b8ee8394bcb'
down_revision = 'bd9a70ee3cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hacker_event_registration',
                  sa.Column('update_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hacker_event_registration', 'update_user')
    # ### end Alembic commands ###
