"""empty message

Revision ID: 66f272fcd052
Revises: bf4093e132a0
Create Date: 2023-09-27 17:02:13.276374

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '66f272fcd052'
down_revision = 'bf4093e132a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column('terms_accepted', sa.Boolean(), nullable=True, default=True))
    #set terms_accepted to true for all users
    op.execute('UPDATE "user" SET terms_accepted = true')
    #set terms_accepted to not nullable
    op.alter_column('user', 'terms_accepted', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'terms_accepted')
    # ### end Alembic commands ###
