"""empty message

Revision ID: 6e8d8784987c
Revises: 871f7124284f
Create Date: 2023-09-16 00:51:20.304360

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6e8d8784987c'
down_revision = '871f7124284f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user',
                  sa.Column('rest_password_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rest_password_token')
    # ### end Alembic commands ###
