"""empty message

Revision ID: 91cc228b8be9
Revises: 7c00e3578952
Create Date: 2023-08-24 03:47:03.289789

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '91cc228b8be9'
down_revision = '7c00e3578952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('refresh_token',
                                    sa.String(),
                                    nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refresh_token')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
