"""empty message

Revision ID: bd9a70ee3cae
Revises: c5d57910d670
Create Date: 2023-09-11 05:00:19.105056

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bd9a70ee3cae'
down_revision = 'c5d57910d670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hacker', 'dailyhack_github_repo')
    op.add_column('hacker_event_registration',
                  sa.Column('dailyhack_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hacker_event_registration', 'dailyhack_url')
    op.add_column(
        'hacker',
        sa.Column('dailyhack_github_repo',
                  sa.VARCHAR(),
                  autoincrement=False,
                  nullable=True))
    # ### end Alembic commands ###
